version: '3.8'
services:
  tomcat:
    hostname: tomcat.lab
    image: 'tomcat:9.0.83'
    volumes:
      - ./data/jsp:/usr/local/tomcat/webapps/webapp
    environment:
      - http_proxy=http://10.20.0.20:8080
      - http_proxys=http://10.20.0.20:8080
    depends_on:
      - mitmproxy
    dns:
      - 10.20.0.23
    networks:
      research:
        ipv4_address: 10.20.0.10

  php5:
    hostname: php5.lab
    image: 'php:5.6.40-apache-stretch'
    volumes:
      - ./data/php:/var/www/html
    environment:
      - http_proxy=http://10.20.0.20:8080
      - http_proxys=http://10.20.0.20:8080
    depends_on:
      - mitmproxy
    dns:
      - 10.20.0.23
    networks:
      research:
        ipv4_address: 10.20.0.15

  php7:
    hostname: php7.lab
    image: 'php:7.4.33-apache-bullseye'
    volumes:
      - ./data/php:/var/www/html
    environment:
      - http_proxy=http://10.20.0.20:8080
      - http_proxys=http://10.20.0.20:8080
    depends_on:
      - mitmproxy
    dns:
      - 10.20.0.23
    networks:
      research:
        ipv4_address: 10.20.0.16

  php8:
    hostname: php8.lab
    image: 'php:8.3-rc-apache-bookworm'
    volumes:
      - ./data/php:/var/www/html
    environment:
      - http_proxy=http://10.20.0.20:8080
      - http_proxys=http://10.20.0.20:8080
    depends_on:
      - mitmproxy
    dns:
      - 10.20.0.23
    networks:
      research:
        ipv4_address: 10.20.0.17
  
  mitmproxy:
    hostname: mitmproxy.lab
    image: 'mitmproxy/mitmproxy:10.1.5'
    command: ["mitmweb", "--web-host", "0.0.0.0"]
    ports:
      - 0.0.0.0:8081:8081
    volumes:
      - mitmproxy:/home/mitmproxy/.mitmproxy
    dns:
      - 10.21.0.23
    depends_on:
      - pihole
    networks:
      public:
        ipv4_address: 10.21.0.20
      research:
        ipv4_address: 10.20.0.20

  sandbox:
    hostname: sandbox.lab
    build:
      context: .
      dockerfile: build/sandbox.Dockerfile
    image: 'csalab/thestrack-sandbox:latest'
    environment:
      - PASSWORD=${PASSWORD:-password}
      - http_proxy=http://10.20.0.20:8080
      - http_proxys=http://10.20.0.20:8080
    volumes:
      - ./data/data:/root/data
    dns:
      - 10.20.0.23
    depends_on:
      - mitmproxy
    networks:
      research:
        ipv4_address: 10.20.0.21

  socat:
    hostname: socat.lab
    image: 'alpine/socat:1.7.4.4'
    ports:
      - 0.0.0.0:9090:9090
    depends_on:
      - sandbox
    entrypoint: ["socat", "TCP-LISTEN:9090,fork", "TCP:10.20.0.21:80"]
    networks:
      public:
        ipv4_address: 10.21.0.22
      research:
        ipv4_address: 10.20.0.22
  
  pihole:
    hostname: pihole.lab
    image: pihole/pihole:latest
    ports:
      - 0.0.0.0:8082:80/tcp
    environment:
      - TZ=Asia/Jakarta
      - WEBPASSWORD=${PASSWORD:-password}
    volumes:
      - pihole_etc:/etc/pihole
      - pihole_dns:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    networks:
      public:
        ipv4_address: 10.21.0.23
      research:
        ipv4_address: 10.20.0.23

  unsandbox:
    hostname: unsandbox.lab
    build:
      context: .
      dockerfile: build/unsandbox.Dockerfile
    image: 'csalab/thestrack-unsandbox:latest'
    ports:
      - 0.0.0.0:9191:80
    environment:
      - PASSWORD=${PASSWORD:-password}
    volumes:
      - ./data/data:/root/data
    dns:
      - 10.21.0.23
    networks:
      public:
        ipv4_address: 10.21.0.24
      research:
        ipv4_address: 10.20.0.24

  server.lab:
    hostname: mail.server.lab
    image: 'csalab/iredmail:latest'
    restart: always
    environment:
      - HOSTNAME=mail.server.lab
      - FIRST_MAIL_DOMAIN=server.lab
      - FIRST_MAIL_DOMAIN_ADMIN_PASSWORD=${MAIL_PASS:-mailpassword}
      - MLMMJADMIN_API_TOKEN=CCmMymMpFH35K8Q0H3FQAsSRQzkSjCeazm+t1X27cdE=
      - ROUNDCUBE_DES_KEY=s9lVEEaiA+MmvYZvfi1k0WQNFiFmGOYI
    volumes:
      - iredmail_backup-mysql:/var/vmail/backup/mysql
      - iredmail_mailboxes:/var/vmail/vmail1
      - iredmail_mlmmj:/var/vmail/mlmmj
      - iredmail_mlmmj_archive:/var/vmail/mlmmj-archive
      - iredmail_imapsieve_copy:/var/vmail/imapsieve_copy
      - iredmail_custom:/opt/iredmail/custom
      - iredmail_ssl:/opt/iredmail/ssl
      - iredmail_mysql:/var/lib/mysql
      - iredmail_clamav:/var/lib/clamav
      - iredmail_sa_rules:/var/lib/spamassassin
      - iredmail_postfix_queue:/var/spool/postfix
    dns:
      - 10.21.0.23
    networks:
      public:
        ipv4_address: 10.21.0.25
      research:
        ipv4_address: 10.20.0.25

  mail-forward:
    image: 'zixia/simple-mail-forwarder:1.4'
    hostname: mail-forward.lab
    restart: always
    environment:
      - SMF_CONFIG=@getnada.com:postmaster@server.lab:mailpassword
    volumes:
      - mail_forward:/var/spool/postfix
    depends_on:
      - server.lab
    networks:
      public:
        ipv4_address: 10.21.0.26
      research:
        ipv4_address: 10.20.0.26

networks:
  public:
    driver: bridge
    ipam:
      config:
        - subnet: 10.21.0.0/24
          gateway: 10.21.0.1
  research:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 10.20.0.0/24
          gateway: 10.20.0.1

volumes:
  pihole_etc: {}
  pihole_dns: {}
  mitmproxy: {}
  iredmail_backup-mysql: {}
  iredmail_mailboxes: {}
  iredmail_mlmmj: {}
  iredmail_mlmmj_archive: {}
  iredmail_imapsieve_copy: {}
  iredmail_custom: {}
  iredmail_ssl: {}
  iredmail_mysql: {}
  iredmail_clamav: {}
  iredmail_sa_rules: {}
  iredmail_postfix_queue: {}
  mail_forward: {}