version: '3.8'
services:
  tomcat:
    container_name: tomcat
    hostname: tomcat.lab
    image: 'tomcat:9.0.83'
    volumes:
      - ./data/tomcat:/usr/local/tomcat/webapps/webapp
    depends_on:
      - mitmproxy
    networks:
      research:
        ipv4_address: 10.20.0.10

  php5:
    container_name: php5
    hostname: php5.lab
    image: 'php:5.6.40-apache-stretch'
    volumes:
      - ./data/php/5:/var/www/html
    depends_on:
      - mitmproxy
    networks:
      research:
        ipv4_address: 10.20.0.15

  php7:
    container_name: php7
    hostname: php7.lab
    image: 'php:7.4.33-apache-bullseye'
    volumes:
      - ./data/php/7:/var/www/html
    depends_on:
      - mitmproxy
    networks:
      research:
        ipv4_address: 10.20.0.16

  php8:
    container_name: php8
    hostname: php8.lab
    image: 'php:8.3-rc-apache-bookworm'
    volumes:
      - ./data/php/8:/var/www/html
    depends_on:
      - mitmproxy
    networks:
      research:
        ipv4_address: 10.20.0.17
  
  mitmproxy:
    container_name: mitmproxy
    hostname: mitmproxy.lab
    image: 'mitmproxy/mitmproxy:10.1.5'
    command: ["mitmweb", "--web-host", "0.0.0.0"]
    networks:
      public:
        ipv4_address: 10.21.0.20
      research:
        ipv4_address: 10.20.0.20

  openbox:
    container_name: openbox
    hostname: openbox.lab
    build:
      context: .
      dockerfile: build/openbox.Dockerfile
    image: 'csalab/barenv-openbox:latest'
    environment:
      - PASSWORD=${PASSWORD:-password}
    depends_on:
      - mitmproxy
    networks:
      research:
        ipv4_address: 10.20.0.21

  socat:
    container_name: socat
    hostname: socat.lab
    image: 'alpine/socat:1.7.4.4'
    ports:
      - 0.0.0.0:9090:9090
    depends_on:
      - openbox
    entrypoint: ["socat", "TCP-LISTEN:9090,fork", "TCP:10.20.0.21:80"]
    networks:
      public:
        ipv4_address: 10.21.0.22
      research:
        ipv4_address: 10.20.0.22

networks:
  public:
    driver: bridge
    ipam:
      config:
        - subnet: 10.21.0.0/24
          gateway: 10.21.0.1
  research:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 10.20.0.0/24
          gateway: 10.20.0.1