version: '3.8'
services:
  unsandbox:
    container_name: unsandbox
    hostname: unsandbox.lab
    image: 'csalab/barenv-unsandbox:latest'
    environment:
      - PASSWORD=${PASSWORD:-password}
    volumes:
      - data:/root/data
    networks:
      public:
        ipv4_address: 10.21.0.24

  cloudflared:
    hostname: cloudflared
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    restart: always
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN:-secret}
    command: ["tunnel", "--no-autoupdate", "run"]
    depends_on:
      - unsandbox
    networks:
      public:
        ipv4_address: 10.21.0.25

networks:
  public:
    driver: bridge
    ipam:
      config:
        - subnet: 10.21.0.0/24
          gateway: 10.21.0.1

volumes:
  data: {}