version: 2.1

parameters:
  workflow:
    type: enum
    default: auto
    description: The workflow to trigger.
    enum: [auto, desktop, php-all, php5, php7, php8, mailhog, all]

executors:
  docker:
    docker:
      - image: cimg/base:stable

jobs:
  hadolint:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Checking thestrack-sandbox docker file code quality
          command: docker run --rm -i ghcr.io/hadolint/hadolint:latest < build/sandbox.Dockerfile || true
      - run:
          name: Checking thestrack-unsandbox docker file code quality
          command: docker run --rm -i ghcr.io/hadolint/hadolint:latest < build/unsandbox.Dockerfile || true
      - run:
          name: Checking thestrack-php5 docker file code quality
          command: docker run --rm -i ghcr.io/hadolint/hadolint:latest < build/php5.Dockerfile || true
      - run:
          name: Checking thestrack-php7 docker file code quality
          command: docker run --rm -i ghcr.io/hadolint/hadolint:latest < build/php7.Dockerfile || true
      - run:
          name: Checking thestrack-php8 docker file code quality
          command: docker run --rm -i ghcr.io/hadolint/hadolint:latest < build/php8.Dockerfile || true
      - run:
          name: Checking thestrack-mailhog docker file code quality
          command: docker run --rm -i ghcr.io/hadolint/hadolint:latest < build/mailhog.Dockerfile || true
  build-sandbox:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build sandbox image
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin $DOCKER_REGISTRY
            export DOCKER_CLI_EXPERIMENTAL=enabled
            docker context create buildx-build
            docker buildx create --use buildx-build
            docker buildx build --push --tag $DOCKER_REGISTRY/$REGISTRY_USER/thestrack-sandbox:$IMAGE_VERSION --platform linux/amd64,linux/arm64 -f build/sandbox.Dockerfile .
  build-unsandbox:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build unsandbox image
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin $DOCKER_REGISTRY
            export DOCKER_CLI_EXPERIMENTAL=enabled
            docker context create buildx-build
            docker buildx create --use buildx-build
            docker buildx build --push --tag $DOCKER_REGISTRY/$REGISTRY_USER/thestrack-unsandbox:$IMAGE_VERSION --platform linux/amd64,linux/arm64 -f build/unsandbox.Dockerfile .
  build-php5:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build php5 image
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin $DOCKER_REGISTRY
            export DOCKER_CLI_EXPERIMENTAL=enabled
            docker context create buildx-build
            docker buildx create --use buildx-build
            docker buildx build --push --tag $DOCKER_REGISTRY/$REGISTRY_USER/thestrack-php5:$IMAGE_VERSION --platform linux/amd64,linux/arm64 -f build/php5.Dockerfile .
  build-php7:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build php7 image
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin $DOCKER_REGISTRY
            export DOCKER_CLI_EXPERIMENTAL=enabled
            docker context create buildx-build
            docker buildx create --use buildx-build
            docker buildx build --push --tag $DOCKER_REGISTRY/$REGISTRY_USER/thestrack-php7:$IMAGE_VERSION --platform linux/amd64,linux/arm64 -f build/php7.Dockerfile .
  build-php8:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build php8 image
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin $DOCKER_REGISTRY
            export DOCKER_CLI_EXPERIMENTAL=enabled
            docker context create buildx-build
            docker buildx create --use buildx-build
            docker buildx build --push --tag $DOCKER_REGISTRY/$REGISTRY_USER/thestrack-php8:$IMAGE_VERSION --platform linux/amd64,linux/arm64 -f build/php8.Dockerfile .
  build-mailhog:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build mailhog image
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin $DOCKER_REGISTRY
            export DOCKER_CLI_EXPERIMENTAL=enabled
            docker context create buildx-build
            docker buildx create --use buildx-build
            docker buildx build --push --tag $DOCKER_REGISTRY/$REGISTRY_USER/thestrack-mailhog:$IMAGE_VERSION --platform linux/amd64,linux/arm64 -f build/mailhog.Dockerfile .

workflows:
  version: 2
  build-image-auto:
    when: { equal: [ auto, << pipeline.parameters.workflow >> ] }
    jobs:
      - hadolint
  build-image-desktop:
    when: { equal: [ desktop, << pipeline.parameters.workflow >> ] }
    jobs:
      - hadolint
      - build-sandbox:
          requires:
            - hadolint
      - build-unsandbox:
          requires:
            - hadolint
  build-image-php-all:
    when: { equal: [ php-all, << pipeline.parameters.workflow >> ] }
    jobs:
      - hadolint
      - build-php5:
          requires:
            - hadolint
      - build-php7:
          requires:
            - hadolint
      - build-php8:
          requires:
            - hadolint
  build-image-all:
    when: { equal: [ all, << pipeline.parameters.workflow >> ] }
    jobs:
      - hadolint
      - build-sandbox:
          requires:
            - hadolint
      - build-unsandbox:
          requires:
            - hadolint
      - build-php5:
          requires:
            - hadolint
      - build-php7:
          requires:
            - hadolint
      - build-php8:
          requires:
            - hadolint
      - build-mailhog:
          requires:
            - hadolint
  build-image-php5:
    when: { equal: [ php5, << pipeline.parameters.workflow >> ] }
    jobs:
      - hadolint
      - build-php5:
          requires:
            - hadolint
  build-image-php7:
    when: { equal: [ php7, << pipeline.parameters.workflow >> ] }
    jobs:
      - hadolint
      - build-php7:
          requires:
            - hadolint
  build-image-php8:
    when: { equal: [ php8, << pipeline.parameters.workflow >> ] }
    jobs:
      - hadolint
      - build-php8:
          requires:
            - hadolint
  build-image-mailhog:
    when: { equal: [ mailhog, << pipeline.parameters.workflow >> ] }
    jobs:
      - hadolint
      - build-mailhog:
          requires:
            - hadolint